"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createClient} from "@/lib/supabase/server";
const back=(l:string,p:string,q:string)=>"/"+l+"/app/projects/"+p+"/finance?"+q;
async function ctx(fd:FormData){const locale=fd.get("locale")==="en"?"en":"th",projectId=String(fd.get("project_id")||"");const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect("/"+locale+"/login");return{locale,projectId,s,user};}
export async function createFinancialDocument(fd:FormData){const {locale,projectId,s,user}=await ctx(fd),type=String(fd.get("document_type")||""),amount=Number(fd.get("amount")||0),date=String(fd.get("document_date")||""),counterparty=String(fd.get("counterparty_name")||"").trim(),category=String(fd.get("cost_category_id")||"")||null,source=String(fd.get("source_document_id")||"")||null,description=String(fd.get("description")||"").trim();const allowed=["COMMITMENT","AP","AR","PAYMENT","RECEIPT"];if(!projectId||!allowed.includes(type)||amount<=0)redirect(back(locale,projectId,"error=transaction"));const {data:p}=await s.from("projects").select("organization_id").eq("id",projectId).single();if(!p)redirect("/"+locale+"/app/projects");if(["COMMITMENT","AP"].includes(type)&&!category)redirect(back(locale,projectId,"error=category"));const no=type+"-"+Date.now().toString(36).toUpperCase();const {error}=await s.from("financial_documents").insert({organization_id:p.organization_id,project_id:projectId,document_type:type,document_no:no,document_date:date||new Date().toISOString().slice(0,10),counterparty_type:type==="RECEIPT"||type==="AR"?"CUSTOMER":"VENDOR",counterparty_name:counterparty||null,cost_category_id:category,source_document_id:source,amount,status:"DRAFT",description,created_by:user.id});if(error)redirect(back(locale,projectId,"error=transaction"));revalidatePath("/"+locale+"/app/projects/"+projectId+"/finance");redirect(back(locale,projectId,"saved=transaction"))}
export async function approveFinancialDocument(fd:FormData){const {locale,projectId,s}=await ctx(fd),documentId=String(fd.get("document_id")||"");const {error}=await s.rpc("approve_financial_document",{target_document:documentId});if(error)redirect(back(locale,projectId,"error=approve"));revalidatePath("/"+locale+"/app/projects/"+projectId+"/finance");redirect(back(locale,projectId,"approved=1"))}
export async function postApprovedFinancialDocument(fd:FormData){const {locale,projectId,s}=await ctx(fd),documentId=String(fd.get("document_id")||"");const {error}=await s.rpc("post_approved_financial_document",{target_document:documentId});if(error)redirect(back(locale,projectId,"error=post"));revalidatePath("/"+locale+"/app/projects/"+projectId+"/finance");redirect(back(locale,projectId,"posted=1"))}
export async function postFinancialDocument(fd:FormData){const {locale,projectId,s}=await ctx(fd),documentId=String(fd.get("document_id")||"");const {error}=await s.rpc("post_financial_document",{target_document:documentId});if(error)redirect(back(locale,projectId,"error=post"));revalidatePath("/"+locale+"/app/projects/"+projectId+"/finance");redirect(back(locale,projectId,"posted=1"))}
export async function createProcurementContract(fd:FormData){const {locale,projectId,s,user}=await ctx(fd),contractType=String(fd.get("contract_type")||""),vendor=String(fd.get("vendor_name")||"").trim(),category=String(fd.get("cost_category_id")||""),amount=Number(fd.get("amount")||0),date=String(fd.get("contract_date")||""),description=String(fd.get("description")||"").trim();if(!["PO","CONTRACT"].includes(contractType)||!vendor||!category||amount<=0)redirect(back(locale,projectId,"error=contract"));const {data:p}=await s.from("projects").select("organization_id").eq("id",projectId).single();if(!p)redirect("/"+locale+"/app/projects");const no=(contractType==="PO"?"PO-":"CT-")+Date.now().toString(36).toUpperCase();const {error}=await s.from("procurement_contracts").insert({organization_id:p.organization_id,project_id:projectId,contract_no:no,contract_type:contractType,vendor_name:vendor,cost_category_id:category,contract_date:date||new Date().toISOString().slice(0,10),amount,status:"DRAFT",description,created_by:user.id});if(error)redirect(back(locale,projectId,"error=contract"));revalidatePath("/"+locale+"/app/projects/"+projectId+"/finance");redirect(back(locale,projectId,"saved=contract"))}
export async function approveProcurementContract(fd:FormData){const {locale,projectId,s}=await ctx(fd),contractId=String(fd.get("contract_id")||"");const {error}=await s.rpc("approve_procurement_contract",{target_contract:contractId});if(error)redirect(back(locale,projectId,"error=contract_approve"));revalidatePath("/"+locale+"/app/projects/"+projectId+"/finance");redirect(back(locale,projectId,"approved=contract"))}
