import Link from "next/link";import{notFound,redirect}from"next/navigation";import{createClient}from"@/lib/supabase/server";import{saveConstruction,saveFinancials,saveSale}from"./actions";import styles from"./unit.module.css";
export default async function Unit360({params,searchParams}:{params:Promise<{locale:string,id:string,unitId:string}>,searchParams:Promise<Record<string,string|undefined>>}){const{locale:raw,id,unitId}=await params,locale=raw==="en"?"en":"th",en=locale==="en",q=await searchParams,s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect(`/${locale}/login`);
const{data:u}=await s.from("units").select("id,code,name,status,list_price,target_completion_date,project_id,projects(name,code),plots(code,land_area_sqm),house_types(code,name,bedrooms,bathrooms,gross_floor_area_sqm),unit_construction(*),unit_financials(*),unit_sales(*,customers(full_name,phone,email))").eq("id",unitId).eq("project_id",id).maybeSingle();if(!u)notFound();
const con=Array.isArray(u.unit_construction)?u.unit_construction[0]:u.unit_construction,fin=Array.isArray(u.unit_financials)?u.unit_financials[0]:u.unit_financials,sale=Array.isArray(u.unit_sales)?u.unit_sales[0]:u.unit_sales;const cust=sale?.customers,fmt=new Intl.NumberFormat(en?"en-US":"th-TH",{maximumFractionDigits:0}),budget=Number(fin?.budget_amount||0),actual=Number(fin?.actual_cost||0),variance=budget?budget-actual:null;
return <main className={styles.page}><header className={styles.hero}><div><Link href={`/${locale}/app/projects/${id}`}>← {en?"Project Workspace":"Project Workspace"}</Link><p>UNIT 360° · {u.code}</p><h1>{u.name||u.code}</h1><span>{(u.projects as any)?.name} · {(u.house_types as any)?.name||"—"} · {(u.plots as any)?.code||"—"}</span></div><div className={styles.price}><small>{en?"LIST PRICE":"ราคาขาย"}</small><b>{u.list_price!==null?"฿"+fmt.format(Number(u.list_price)):"—"}</b><em>{u.status}</em></div></header>
{q.saved&&<div className={styles.ok}>✓ {en?"Saved":"บันทึกแล้ว"} · {q.saved}</div>}{q.error&&<div className={styles.err}>! {en?"Could not save":"บันทึกไม่สำเร็จ"} · {q.error}</div>}
<section className={styles.kpis}><article><small>CONSTRUCTION</small><b>{Number(con?.progress_percent||0)}%</b><div><i style={{width:`${Number(con?.progress_percent||0)}%`}}/></div></article><article><small>{en?"BUDGET":"งบประมาณ"}</small><b>{fin?.budget_amount!==null&&fin?.budget_amount!==undefined?"฿"+fmt.format(budget):"—"}</b><em>{variance===null?"—":variance>=0?`฿${fmt.format(variance)} under`:`฿${fmt.format(Math.abs(variance))} over`}</em></article><article><small>SALES</small><b>{sale?.status||u.status}</b><em>{cust?.full_name|| (en?"No customer":"ยังไม่มีลูกค้า")}</em></article><article><small>{en?"HOUSE TYPE":"แบบบ้าน"}</small><b>{(u.house_types as any)?.code||"—"}</b><em>{(u.house_types as any)?.bedrooms??0} BR · {(u.house_types as any)?.bathrooms??0} BA · {(u.house_types as any)?.gross_floor_area_sqm??"—"} m²</em></article></section>
<div className={styles.grid}>
<section className={styles.card}><Head n="01" t={en?"Construction":"งานก่อสร้าง"}/><form action={saveConstruction} className={styles.form}><Hidden l={locale} p={id} u={unitId}/><label>{en?"Stage":"ขั้นงาน"}<select name="stage" defaultValue={con?.stage||"NOT_STARTED"}>{["NOT_STARTED","FOUNDATION","STRUCTURE","ROOF","MEP","FINISHING","INSPECTION","COMPLETED"].map(x=><option key={x}>{x}</option>)}</select></label><label>{en?"Progress %":"ความคืบหน้า %"}<input name="progress_percent" type="number" min="0" max="100" step=".01" defaultValue={con?.progress_percent??0}/></label><label>{en?"Start date":"วันเริ่ม"}<input name="start_date" type="date" defaultValue={con?.start_date??""}/></label><label>{en?"Target completion":"กำหนดเสร็จ"}<input name="target_completion_date" type="date" defaultValue={con?.target_completion_date??u.target_completion_date??""}/></label><label className={styles.full}>{en?"Notes":"หมายเหตุ"}<textarea name="notes" defaultValue={con?.notes??""}/></label><button>{en?"Save Construction":"บันทึกงานก่อสร้าง"}</button></form></section>
<section className={styles.card}><Head n="02" t={en?"Cost & Budget":"ต้นทุนและงบประมาณ"}/><form action={saveFinancials} className={styles.form}><Hidden l={locale} p={id} u={unitId}/><label>{en?"Budget":"งบประมาณ"}<input name="budget_amount" type="number" min="0" step=".01" defaultValue={fin?.budget_amount??""}/></label><label>{en?"Committed":"ยอดผูกพัน"}<input name="committed_amount" type="number" min="0" step=".01" defaultValue={fin?.committed_amount??0}/></label><label>{en?"Actual cost":"ต้นทุนจริง"}<input name="actual_cost" type="number" min="0" step=".01" defaultValue={fin?.actual_cost??0}/></label><div className={styles.costbox}><span>{en?"Variance":"ส่วนต่าง"}</span><b>{variance===null?"—":(variance>=0?"+":"-")+"฿"+fmt.format(Math.abs(variance))}</b></div><button>{en?"Save Financials":"บันทึกต้นทุน"}</button></form></section>
<section className={styles.cardWide}><Head n="03" t={en?"Sales & Customer":"การขายและลูกค้า"}/><form action={saveSale} className={styles.saleForm}><Hidden l={locale} p={id} u={unitId}/><label>{en?"Sales status":"สถานะขาย"}<select name="status" defaultValue={sale?.status||u.status}>{["AVAILABLE","HOLD","RESERVED","CONTRACTED","SOLD","TRANSFERRED"].map(x=><option key={x}>{x}</option>)}</select></label><label>{en?"Agreed price":"ราคาตกลง"}<input name="agreed_price" type="number" min="0" step=".01" defaultValue={sale?.agreed_price??""}/></label><label>{en?"Customer":"ชื่อลูกค้า"}<input name="customer_name" defaultValue={cust?.full_name??""}/></label><label>{en?"Phone":"โทรศัพท์"}<input name="phone" defaultValue={cust?.phone??""}/></label><label>{en?"Email":"อีเมล"}<input name="email" type="email" defaultValue={cust?.email??""}/></label><label>{en?"Reservation":"วันจอง"}<input name="reservation_date" type="date" defaultValue={sale?.reservation_date??""}/></label><label>{en?"Contract":"วันทำสัญญา"}<input name="contract_date" type="date" defaultValue={sale?.contract_date??""}/></label><label>{en?"Transfer":"วันโอน"}<input name="transfer_date" type="date" defaultValue={sale?.transfer_date??""}/></label><label className={styles.full}>{en?"Notes":"หมายเหตุ"}<textarea name="notes" defaultValue={sale?.notes??""}/></label><button>{en?"Save Sales":"บันทึกการขาย"}</button></form></section>
</div></main>}
function Head({n,t}:{n:string,t:string}){return <div className={styles.head}><span>{n}</span><h2>{t}</h2></div>}function Hidden({l,p,u}:{l:string,p:string,u:string}){return <><input type="hidden" name="locale" value={l}/><input type="hidden" name="project_id" value={p}/><input type="hidden" name="unit_id" value={u}/></>}
