"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

async function ctx(formData:FormData){
 const locale=formData.get("locale")==="en"?"en":"th"; const projectId=String(formData.get("project_id")??"");
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect(`/${locale}/login`);
 if(!projectId) redirect(`/${locale}/app/projects`); return {locale,projectId,supabase};
}
function done(locale:string,id:string){revalidatePath(`/${locale}/app`);revalidatePath(`/${locale}/app/projects`);revalidatePath(`/${locale}/app/projects/${id}`);redirect(`/${locale}/app/projects/${id}?saved=1`)}
export async function addPhase(fd:FormData){const {locale,projectId,supabase}=await ctx(fd);const code=String(fd.get("code")??"").trim().toUpperCase(),name=String(fd.get("name")??"").trim(),sequence_no=Number(fd.get("sequence_no")||1);if(!code||!name)redirect(`/${locale}/app/projects/${projectId}?error=phase`);const {error}=await supabase.from("phases").insert({project_id:projectId,code,name,sequence_no});if(error)redirect(`/${locale}/app/projects/${projectId}?error=phase`);done(locale,projectId)}
export async function addPlot(fd:FormData){const {locale,projectId,supabase}=await ctx(fd);const code=String(fd.get("code")??"").trim().toUpperCase(),phase_id=String(fd.get("phase_id")??"")||null,area=String(fd.get("land_area_sqm")??"");if(!code)redirect(`/${locale}/app/projects/${projectId}?error=plot`);const {error}=await supabase.from("plots").insert({project_id:projectId,phase_id,code,land_area_sqm:area?Number(area):null});if(error)redirect(`/${locale}/app/projects/${projectId}?error=plot`);done(locale,projectId)}
export async function addHouseType(fd:FormData){const {locale,projectId,supabase}=await ctx(fd);const {data:p}=await supabase.from("projects").select("organization_id").eq("id",projectId).single();if(!p)redirect(`/${locale}/app/projects/${projectId}?error=type`);const code=String(fd.get("code")??"").trim().toUpperCase(),name=String(fd.get("name")??"").trim();if(!code||!name)redirect(`/${locale}/app/projects/${projectId}?error=type`);const {error}=await supabase.from("house_types").insert({organization_id:p.organization_id,code,name,bedrooms:Number(fd.get("bedrooms")||0),bathrooms:Number(fd.get("bathrooms")||0),gross_floor_area_sqm:fd.get("gross_floor_area_sqm")?Number(fd.get("gross_floor_area_sqm")):null});if(error)redirect(`/${locale}/app/projects/${projectId}?error=type`);done(locale,projectId)}
export async function addUnit(fd:FormData){const {locale,projectId,supabase}=await ctx(fd);const code=String(fd.get("code")??"").trim().toUpperCase();if(!code)redirect(`/${locale}/app/projects/${projectId}?error=unit`);const val=(k:string)=>String(fd.get(k)??"")||null;const price=String(fd.get("list_price")??"");const {error}=await supabase.from("units").insert({project_id:projectId,phase_id:val("phase_id"),plot_id:val("plot_id"),house_type_id:val("house_type_id"),code,name:val("name"),status:String(fd.get("status")||"AVAILABLE"),list_price:price?Number(price):null,currency_code:"THB"});if(error)redirect(`/${locale}/app/projects/${projectId}?error=unit`);done(locale,projectId)}
