import Link from "next/link";import {notFound,redirect} from "next/navigation";import {createClient} from "@/lib/supabase/server";import {addPhase,addPlot,addHouseType,addUnit} from "./actions";import styles from "./project.module.css";
export default async function ProjectDetail({params,searchParams}:{params:Promise<{locale:string,id:string}>,searchParams:Promise<Record<string,string|undefined>>}){const {locale:raw,id}=await params;const locale=raw==="en"?"en":"th",en=locale==="en",q=await searchParams;const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect(`/${locale}/login`);
const {data:p}=await s.from("projects").select("id,organization_id,code,name,status,target_completion_date,phases(id,code,name,sequence_no),plots(id,code,land_area_sqm,phase_id),units(id,code,name,status,list_price,plot_id,phase_id,house_type_id)").eq("id",id).maybeSingle();if(!p)notFound();const {data:types}=await s.from("house_types").select("id,code,name,bedrooms,bathrooms,gross_floor_area_sqm").eq("organization_id",p.organization_id).order("code");const phases=[...(p.phases??[])].sort((a,b)=>a.sequence_no-b.sequence_no),plots=p.plots??[],units=p.units??[],houseTypes=types??[];const money=new Intl.NumberFormat(en?"en-US":"th-TH",{maximumFractionDigits:0});
return <main className={styles.page}><header className={styles.hero}><div><Link href={`/${locale}/app/projects`}>← {en?"All Projects":"โครงการทั้งหมด"}</Link><p>{p.code} · {p.status}</p><h1>{p.name}</h1><span>{en?"Project structure & inventory":"โครงสร้างโครงการและ Inventory"}</span></div><div className={styles.heroStats}><b>{phases.length}<small>PHASES</small></b><b>{plots.length}<small>PLOTS</small></b><b>{units.length}<small>UNITS</small></b></div></header>
{q.saved&&<div className={styles.ok}>✓ {en?"Saved successfully":"บันทึกข้อมูลเรียบร้อย"}</div>}{q.error&&<div className={styles.err}>! {en?"Could not save this item. Check duplicate codes or permissions.":"บันทึกไม่สำเร็จ กรุณาตรวจรหัสซ้ำหรือสิทธิ์การใช้งาน"}</div>}
<section className={styles.flow}><span>PROJECT</span><i>→</i><span>PHASE</span><i>→</i><span>PLOT</span><i>→</i><span>UNIT</span><i>→</i><span>SALE / BUILD</span></section>
<div className={styles.grid}>
<section className={styles.card}><Head n="01" title={en?"Phases":"เฟสโครงการ"}/><div className={styles.rows}>{phases.map(x=><div className={styles.row} key={x.id}><i>{x.sequence_no}</i><span><small>{x.code}</small><b>{x.name}</b></span></div>)}</div><form action={addPhase} className={styles.form}><Hidden locale={locale} id={id}/><input name="code" placeholder="PH-02" required/><input name="name" placeholder={en?"Phase name":"ชื่อเฟส"} required/><input name="sequence_no" type="number" min="1" defaultValue={phases.length+1}/><button>＋ {en?"Add Phase":"เพิ่มเฟส"}</button></form></section>
<section className={styles.card}><Head n="02" title={en?"House Types":"แบบบ้าน"}/><div className={styles.rows}>{houseTypes.map(x=><div className={styles.row} key={x.id}><i>⌂</i><span><small>{x.code}</small><b>{x.name}</b><em>{x.bedrooms??0} BR · {x.bathrooms??0} BA · {x.gross_floor_area_sqm??"—"} m²</em></span></div>)}</div><form action={addHouseType} className={styles.form}><Hidden locale={locale} id={id}/><input name="code" placeholder="TYPE-A" required/><input name="name" placeholder={en?"Type name":"ชื่อแบบบ้าน"} required/><div className={styles.triple}><input name="bedrooms" type="number" min="0" placeholder="BR"/><input name="bathrooms" type="number" min="0" step=".5" placeholder="BA"/><input name="gross_floor_area_sqm" type="number" min="0" step=".01" placeholder="m²"/></div><button>＋ {en?"Add Type":"เพิ่มแบบบ้าน"}</button></form></section>
<section className={styles.card}><Head n="03" title={en?"Plots / Land":"แปลงที่ดิน"}/><div className={styles.rows}>{plots.map(x=><div className={styles.row} key={x.id}><i>◇</i><span><small>{phases.find(f=>f.id===x.phase_id)?.code??"NO PHASE"}</small><b>{x.code}</b><em>{x.land_area_sqm?money.format(Number(x.land_area_sqm))+" m²":"—"}</em></span></div>)}</div><form action={addPlot} className={styles.form}><Hidden locale={locale} id={id}/><input name="code" placeholder="PLOT-06" required/><select name="phase_id"><option value="">{en?"No phase":"ไม่ระบุเฟส"}</option>{phases.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select><input name="land_area_sqm" type="number" min="0" step=".01" placeholder={en?"Land m²":"พื้นที่ m²"}/><button>＋ {en?"Add Plot":"เพิ่มแปลง"}</button></form></section>
<section className={styles.cardWide}><Head n="04" title={en?"Units / Inventory":"ยูนิต / Inventory"}/><div className={styles.units}>{units.map(x=><article key={x.id}><div><small>{x.code}</small><b>{x.name||x.code}</b><em>{plots.find(z=>z.id===x.plot_id)?.code??"—"} · {houseTypes.find(z=>z.id===x.house_type_id)?.name??"—"}</em></div><span>{x.status}</span><strong>{x.list_price!==null?"฿"+money.format(Number(x.list_price)):"—"}</strong></article>)}</div><form action={addUnit} className={styles.unitForm}><Hidden locale={locale} id={id}/><input name="code" placeholder="UNIT-006" required/><input name="name" placeholder={en?"Unit name":"ชื่อยูนิต"}/><select name="phase_id"><option value="">Phase —</option>{phases.map(x=><option value={x.id} key={x.id}>{x.code}</option>)}</select><select name="plot_id"><option value="">Plot —</option>{plots.map(x=><option value={x.id} key={x.id}>{x.code}</option>)}</select><select name="house_type_id"><option value="">House Type —</option>{houseTypes.map(x=><option value={x.id} key={x.id}>{x.code}</option>)}</select><select name="status" defaultValue="AVAILABLE">{["AVAILABLE","HOLD","RESERVED","CONTRACTED","SOLD","TRANSFERRED","UNAVAILABLE"].map(x=><option key={x}>{x}</option>)}</select><input name="list_price" type="number" min="0" step=".01" placeholder={en?"List price":"ราคาขาย"}/><button>＋ {en?"Add Unit":"เพิ่มยูนิต"}</button></form></section>
</div></main>}
function Head({n,title}:{n:string,title:string}){return <div className={styles.head}><span>{n}</span><h2>{title}</h2></div>}function Hidden({locale,id}:{locale:string,id:string}){return <><input type="hidden" name="locale" value={locale}/><input type="hidden" name="project_id" value={id}/></>}
