-- M1 Permission Engine v2
-- System catalog + custom role metadata + per-user ALLOW/DENY overrides + effective permission resolver.
create table if not exists public.permission_catalog(id uuid primary key default gen_random_uuid(),module_code text not null,action_code text not null,name_th text not null,name_en text not null,sort_order int not null default 0,is_active boolean not null default true,unique(module_code,action_code));
alter table public.permission_catalog enable row level security;
create policy "permission catalog readable" on public.permission_catalog for select to authenticated using(true);
alter table public.roles add column if not exists description text;
alter table public.roles add column if not exists is_template boolean not null default false;
create table if not exists public.membership_permission_overrides(id uuid primary key default gen_random_uuid(),membership_id uuid not null references public.organization_memberships(id) on delete cascade,module_code text not null,action_code text not null,effect text not null check(effect in('ALLOW','DENY')),scope_type text not null default 'ORGANIZATION' check(scope_type in('ORGANIZATION','PROJECT')),scope_id uuid,created_at timestamptz not null default now(),unique(membership_id,module_code,action_code,scope_type,scope_id));
alter table public.membership_permission_overrides enable row level security;
create policy "overrides visible to org managers" on public.membership_permission_overrides for select to authenticated using(exists(select 1 from organization_memberships m where m.id=membership_id and can_manage_organization(m.organization_id)));
create policy "overrides managed by org managers" on public.membership_permission_overrides for all to authenticated using(exists(select 1 from organization_memberships m where m.id=membership_id and can_manage_organization(m.organization_id))) with check(exists(select 1 from organization_memberships m where m.id=membership_id and can_manage_organization(m.organization_id)));
-- Catalog is seeded explicitly by application migration deployment.
create or replace function public.has_effective_permission(target_org uuid,target_project uuid,target_module text,target_action text) returns boolean language sql stable security definer set search_path=public as $$ with me as(select id from organization_memberships where organization_id=target_org and user_id=auth.uid() and status='ACTIVE'),deny as(select 1 from membership_permission_overrides o join me on me.id=o.membership_id where o.module_code=target_module and o.action_code=target_action and o.effect='DENY' and(o.scope_type='ORGANIZATION' or(o.scope_type='PROJECT' and o.scope_id=target_project))),allow_override as(select 1 from membership_permission_overrides o join me on me.id=o.membership_id where o.module_code=target_module and o.action_code=target_action and o.effect='ALLOW' and(o.scope_type='ORGANIZATION' or(o.scope_type='PROJECT' and o.scope_id=target_project))),role_allow as(select 1 from me join membership_roles mr on mr.membership_id=me.id join role_permissions rp on rp.role_id=mr.role_id where rp.module_code=target_module and rp.action_code=target_action and(mr.scope_type='ORGANIZATION' or(mr.scope_type='PROJECT' and mr.scope_id=target_project))) select not exists(select 1 from deny) and(exists(select 1 from allow_override) or exists(select 1 from role_allow)); $$;
revoke all on function public.has_effective_permission(uuid,uuid,text,text) from public,anon;grant execute on function public.has_effective_permission(uuid,uuid,text,text) to authenticated;