create table if not exists public.project_feasibility(
 id uuid primary key default gen_random_uuid(), project_id uuid not null unique references projects(id), organization_id uuid not null references organizations(id), target_revenue numeric(18,2) not null default 0, target_cost numeric(18,2) not null default 0, financing_cost numeric(18,2) not null default 0, tax_transfer_cost numeric(18,2) not null default 0, contingency_amount numeric(18,2) not null default 0, target_start_date date, target_end_date date, notes text, updated_by uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.cashflow_forecast_lines(
 id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id), organization_id uuid not null references organizations(id), forecast_month date not null, inflow_sales numeric(18,2) not null default 0, inflow_other numeric(18,2) not null default 0, outflow_land numeric(18,2) not null default 0, outflow_construction numeric(18,2) not null default 0, outflow_operating numeric(18,2) not null default 0, outflow_finance_tax numeric(18,2) not null default 0, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,forecast_month));
create index if not exists cashflow_forecast_project_month_idx on cashflow_forecast_lines(project_id,forecast_month);
alter table project_feasibility enable row level security; alter table cashflow_forecast_lines enable row level security;
create policy project_feasibility_select on project_feasibility for select to authenticated using(can_access_project(project_id));
create policy project_feasibility_manage on project_feasibility for all to authenticated using(can_manage_organization(organization_id) and can_access_project(project_id)) with check(can_manage_organization(organization_id) and can_access_project(project_id));
create policy cashflow_forecast_select on cashflow_forecast_lines for select to authenticated using(can_access_project(project_id));
create policy cashflow_forecast_manage on cashflow_forecast_lines for all to authenticated using(can_manage_organization(organization_id) and can_access_project(project_id)) with check(can_manage_organization(organization_id) and can_access_project(project_id));