create table if not exists public.cost_allocation_runs(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id), project_id uuid not null references projects(id), source_document_id uuid references financial_documents(id), allocation_no text not null, allocation_date date not null default current_date, method text not null check(method in('LAND_AREA','GFA','SALES_VALUE','MANUAL')), source_amount numeric(18,2) not null check(source_amount>0), status text not null default 'DRAFT' check(status in('DRAFT','POSTED','VOID')), description text, created_by uuid references profiles(id), posted_by uuid references profiles(id), created_at timestamptz not null default now(), posted_at timestamptz, unique(project_id,allocation_no));
create table if not exists public.cost_allocation_lines(
 id uuid primary key default gen_random_uuid(), allocation_run_id uuid not null references cost_allocation_runs(id) on delete cascade, unit_id uuid not null references units(id), basis_value numeric(18,4) not null default 0 check(basis_value>=0), allocation_percent numeric(9,6) not null check(allocation_percent>=0 and allocation_percent<=100), allocated_amount numeric(18,2) not null check(allocated_amount>=0), created_at timestamptz not null default now(), unique(allocation_run_id,unit_id));
create index if not exists cost_allocation_runs_project_idx on cost_allocation_runs(project_id,status,allocation_date desc);
create index if not exists cost_allocation_lines_unit_idx on cost_allocation_lines(unit_id);
alter table cost_allocation_runs enable row level security; alter table cost_allocation_lines enable row level security;
create policy cost_allocation_runs_select on cost_allocation_runs for select to authenticated using(can_access_project(project_id));
create policy cost_allocation_runs_manage on cost_allocation_runs for all to authenticated using(can_manage_organization(organization_id) and can_access_project(project_id)) with check(can_manage_organization(organization_id) and can_access_project(project_id));
create policy cost_allocation_lines_select on cost_allocation_lines for select to authenticated using(exists(select 1 from cost_allocation_runs r where r.id=allocation_run_id and can_access_project(r.project_id)));
create policy cost_allocation_lines_manage on cost_allocation_lines for all to authenticated using(exists(select 1 from cost_allocation_runs r where r.id=allocation_run_id and can_manage_organization(r.organization_id) and can_access_project(r.project_id))) with check(exists(select 1 from cost_allocation_runs r where r.id=allocation_run_id and can_manage_organization(r.organization_id) and can_access_project(r.project_id)));